---
title: "Day 5"
author: "Jan Savinc"
date: "23/04/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries

```{r}
library(tidyverse)
library(lubridate)
library(tictoc)
library(survival)
library(survminer)  # for ggplot plots of survival
```

# Load data

```{r}
load(file = "../AALHD_2021/R Syntax and Data/R Data/interim tables/PBSdata3.RData")
load(file = "../AALHD_2021/R Syntax and Data/R Data/diabsupp.RData")
load(file = "../AALHD_2021/R Syntax and Data/R Data/interim tables/diabetes8.RData")

## convert data frames to tibbles for easier looking up while coding
PBSdata3 <- as_tibble(PBSdata3)
diabsupp <- as_tibble(diabsupp)
diabetes8 <- as_tibble(diabetes8)
```


# Define inclusion codes

```{r}
codes_pbs_statins <- c(1224, 1453, 1687, 1942,  2011, 2012, 2013, 2831, 2833, 2834, 2892, 2967, 2978, 8023, 8024, 8173, 8197, 8213, 8214, 8215, 8303, 8304, 8313, 8419, 8521, 8721, 8722, 8757)

make_regex_from_codes <- function(codes) {
  codes %>%
    str_remove_all(string = ., pattern="\\.X$") %>%  # remove final .X wildcard, not needed for regex matching!
    str_replace_all(string = ., pattern = "\\.", replacement = "\\\\.") %>%  # replace dot with string literal dot
    paste0("^", ., collapse = "|")
}
```

# Steps 1-2

```{r}
PBSstatin <-
  PBSdata3 %>%
  mutate(anystatin = pbsitem %in% codes_pbs_statins) %>%
  group_by(rootlpno) %>%
  mutate(statseq = if_else(condition = anystatin, true = cumsum(anystatin), false = NA_integer_)) %>%
  ungroup %>%
  filter(statseq==1) %>%
  select(rootlpno, statdate=dispdate)

stopifnot(nrow(PBSstatin)==3624)
```

# Steps 3-4

```{r}
diabetes8 %>%
  left_join(PBSstatin, by="rootlpno") %>%
  mutate(
    statin = case_when(
      statdate < date ~ 9L,
      as.integer(statdate-date,units="days") %in% 0:364 ~ 1L,
      TRUE ~ 0L,
      )
  ) %>%
  count(statin)

diabetes9 <-
  diabetes8 %>%
  left_join(PBSstatin, by="rootlpno") %>%
  mutate(
    statin = case_when(
      statdate < date ~ 9L,
      as.integer(statdate-date,units="days") %in% 0:364 ~ 1L,
      TRUE ~ 0L,
      )
  ) %>%
  filter(statin!=9) %>%
  mutate(
    year = year(date)
  ) %>%
  filter(year>=1991)

diabetes9 %>%
  count(statin)

stopifnot(nrow(diabetes9)==8263)
```

# Steps 5-6

```{r}
diabetes10 <-
  diabetes9 %>%
  left_join(
    diabsupp, by = "rootlpno"
  ) %>%
  mutate(
    stage = case_when(  # this works because records are partitioned - next statement is evaluated only if 1st one not matched, etc
      stgpt1 > 0 ~ 1L,
      stgpt2 > 0 ~ 2L,
      stgpt3 > 0 ~ 3L,
      TRUE ~ NA_integer_
    )
  )

stopifnot(sum(diabetes10$stage==1) == 5489)
stopifnot(sum(diabetes10$stage==2) == 2291)
stopifnot(sum(diabetes10$stage==3) == 483)
```

# Step 7

```{r}
diabstat <-
  diabetes10 %>%
  mutate(
    surv3 = as.integer(exit - date, units = "days"),
    surv3 = if_else(condition = surv3 > (3*365), true = as.integer(3*365), false = surv3),  # TODO: change 0 to 0.5 if needed!
    # dead3 = as.integer(as.integer(exit - date, units = "days") <= 3*365)
    dead3 = if_else(condition = as.integer(exit - date, units = "days") > 3*365, true = 0, false = dead)  # set dead3 to dead, and replace with 0 if exit more than 3 years after date1
  ) %>%
  filter(year < 1998) %>%
  select(rootlpno, sex, age, statin, year, seifagp, ariagp, macss, stage, surv3, dead3)

stopifnot(nrow(diabstat)==6795)
```

# Step 8

```{r}
survival_object <- survfit(Surv(surv3, dead3) ~ statin, data = diabstat)
cox_step8 <- coxph(Surv(surv3, dead3) ~ statin, data = diabstat)

exp(coef(cox_step8))
```

# Step 9

```{r}
diabstat_recoded <-
  diabstat %>%
  mutate(
    sex = if_else(condition = sex==2, true = 0, false = as.numeric(sex)),  # recode 2 to 0 (female)
    sex = replace_na(sex, 0.5),
    age = replace_na(age, 59.2),
    agem2 = 1 / (age^2),
    agesqrt = sqrt(age),
    anycom = as.integer(macss>0),
    macssln = log(macss + 0.01),  # adjust so it's not 0!
    stage2 = as.integer(stage==2),
    stage3 = as.integer(stage==3),
    seifa25 = case_when(
      seifagp == 1 ~ 0L,
      seifagp %in% 2:5 ~ 1L,
      TRUE ~ NA_integer_
    ),
    aria5 = case_when(
      ariagp %in% 1:4 ~ 0L,
      ariagp == 5 ~ 1L,
      TRUE ~ NA_integer_
    )
  )

cox_step9 <- coxph(Surv(surv3, dead3) ~ statin + sex + agem2 + agesqrt + stage2 + stage3 + anycom + macssln + seifa25 + aria5, data = diabstat_recoded)
exp(coef(cox_step9))
```

# Step 10

```{r}
diabstat %>% count(year, statin) %>% group_by(year) %>% mutate(percent = scales::percent(n / sum(n), accuracy = 0.1))
```

# Step 11

```{r}
cox_step11_linearyear <- coxph(Surv(surv3, dead3) ~ year, data = diabstat_recoded)
cox_step11_discrete <- coxph(Surv(surv3, dead3) ~ factor(year), data = diabstat_recoded)
```

# Step 12

```{r}
logistic_step12 <- glm(statin ~ sex + age + stage2 + stage3 + macss + anycom, data = diabstat_recoded, family="binomial")
exp(coef(logistic_step12))

diabstat_recoded <-
  diabstat_recoded %>%
  mutate(
    propen =
      coef(logistic_step12)["sex"] * sex +
      coef(logistic_step12)["age"] * age +
      coef(logistic_step12)["stage2"] * stage2 +
      coef(logistic_step12)["stage3"] * stage3 +
      coef(logistic_step12)["macss"] * macss +
      coef(logistic_step12)["anycom"] * anycom
  )

diabstat_recoded %>%
  summarise(
    mean = mean(propen),
    sd = sd(propen)
  )

diabstat_recoded %>%
  summarise(
    quants = quantile(propen, c(0.2,0.4,0.6,0.8))
  )

diabstat_recoded <-
  diabstat_recoded %>%
  mutate(
    # propengp = ntile(propen, n = 5)
    propengp = cut(x = propen, breaks = quantile(propen, c(0,0.2,0.4,0.6,0.8,1)), include.lowest = TRUE, labels = 1:5)
  )

diabstat_recoded %>% count(propengp, statin) %>% group_by(propengp) %>% mutate(percent = scales::percent(n / sum(n), accuracy = 0.1))
```

# Step 13

```{r}
diabstat_recoded <-
  diabstat_recoded %>%
  mutate(
    lopropen = if_else(condition = propengp %in% 1:2, true = 1L, false = 0L),
    intstlo = statin * lopropen
    )

cox_step13 <- coxph(Surv(surv3, dead3) ~ statin + sex + agem2 + agesqrt + stage2 + stage3 + anycom + macssln + seifa25 + aria5 + lopropen + intstlo, data = diabstat_recoded)
exp(coef(cox_step13))
```

# Step 14

```{r}
cox_step14_low_propensity_score <- coxph(Surv(surv3, dead3) ~ statin + sex + agem2 + agesqrt + stage2 + stage3 + anycom + macssln + seifa25 + aria5, data = diabstat_recoded %>% filter(lopropen==1))
exp(coef(cox_step14_low_propensity_score))

cox_step14_high_propensity_score <- coxph(Surv(surv3, dead3) ~ statin + sex + agem2 + agesqrt + stage2 + stage3 + anycom + macssln + seifa25 + aria5, data = diabstat_recoded %>% filter(lopropen==0))
exp(coef(cox_step14_high_propensity_score))
```

A: MRR = 0.73 (average person)

B: 